<?php

namespace AppBundle\Repository;

/**
 * QRCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QRCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
