<?php

namespace AppBundle\Repository;

/**
 * RulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RulesRepository extends \Doctrine\ORM\EntityRepository
{
}
