<?php

namespace AppBundle\Repository;

/**
 * Students_AbscenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Students_AbscenceRepository extends \Doctrine\ORM\EntityRepository
{
}
