<?php

namespace AppBundle\Repository;

/**
 * Students_AttendanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Students_AttendanceRepository extends \Doctrine\ORM\EntityRepository
{
}
