
app-api:
    resource: '@AppBundle/Controller/Api'
    type: annotation
api_login:
    path: /api/login
#REST
users:
    type:     rest
    resource: AppBundle\Controller\Api\UserController
    prefix: /api
tracks:
    type:     rest
    resource: AppBundle\Controller\Api\TrackController
    prefix: /api
branches:
    type:     rest
    resource: AppBundle\Controller\Api\BranchController
    prefix: /api
rules:
    type:     rest
    resource: AppBundle\Controller\Api\RuleController
    prefix: /api
attendance:
    type:     rest
    resource: AppBundle\Controller\Api\AttendanceController
    prefix: /api
#qrcode:
#    type:     rest
#    resource: AppBundle\Controller\Api\QRController
#    prefix: /api

#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_regi0ster:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_change_password:
#     resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#     prefix: /profile

#EndroidQrCodeBundle:
#    resource: "@EndroidQrCodeBundle/Controller/"
#    type:     annotation
#    prefix:   /qrcode
app-web:
    resource: '@AppBundle/Controller/Web'
    type: annotation