# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_API]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        jwt:
            lexik_jwt:
                  class: AppBundle\Entity\User

    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        register:
                pattern: ^/api/register
                anonymous: true
                stateless: true
        qrcode:
                pattern: ^/api/qrcode
                anonymous: true
                stateless: true
        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
#        main:
#            pattern: ^/
#            form_login:
#                provider: fos_userbundle
#                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
#            logout:       true
#            anonymous:    true

    access_control:
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/qrcode,       roles:  IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles:  IS_AUTHENTICATED_FULLY }
