# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    webpack.manifest: "%kernel.root_dir%/../web/dist/manifest.json" #should be absolute
    webpack.public_path_js: /dist/
    webpack.public_path_css: /dist/

services:
  app.form.registration:
     class: AppBundle\Form\RegistrationType
     tags:
         - { name: form.type, alias: app_user_registration }
  heroku.scheduler:
          class: AppBundle\EventListener\HerokuSchedulerSubscriber
          tags:
              - { name: herokue.scheduler, alias: app_heroku_scheduler }

  app.event.authentication_success_listener:
      class: AppBundle\EventListener\AuthenticationSuccessListener
      tags:
         - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
  twig_extension.webpack:
          class: Fullpipe\TwigWebpackExtension\WebpackExtension
          public: false
          arguments:
              - "%webpack.manifest%"
              - "%webpack.public_path_js%"
              - "%webpack.public_path_css%"
          tags:
              - { name: twig.extension }